version: '3.5'

services:
    
    mongodb:
        container_name: mongodb
        image: mongo:latest
        ports:
            - "${MONGO_PORT}:27017"
        restart: unless-stopped
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        volumes:
            - mongodb_data:/data/db

volumes:
    mongodb_data: