version: '3.5'

services:
    
    mongo:
        image: mongo:latest
        container_name: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 1
        ports:
            - "27017:27017"
    
    redis:
        image: redis:latest
        container_name: redis-orion
        ports:
            - "${REDIS_PORT}:6379"
            
    minio:
        image: quay.io/minio/minio:latest
        container_name: minio-orion
        ports:
            - "9000:9000"  # API MinIO
            - "9090:9090"  # Web UI MinIO
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: minioadmin
        command: server /data --console-address ":9090"