server:
    port: ${PORT:5000}
    servlet:
        context-path: ${CONTEXT_PATH:/}
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    tomcat:
        max-http-form-post-size: 10MB
    error:
        whitelabel:
            enabled: false

spring:
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    
    application:
        name: ${APPLICATION_NAME}
    
    data:
        mongodb:
            host: localhost
            port: 27017
            database: orion
            username: admin
            password: admin
            authentication-database: admin
    
    cache:
        type: redis
        redis:
            time-to-live: 600s
    
    jackson:
        default-property-inclusion: non_null
        
    http:
        client:
            connect-timeout: ${HTTP_CLIENT_CONNECT_TIMEOUT:10000}
            read-timeout: ${HTTP_CLIENT_READ_TIMEOUT:10000}

springdoc:
    api-docs:
        enabled: ${SWAGGER_ENABLED:true}
    model-and-view-allowed: true

logging:
    level:
        brave.Tracer: off
        org.springframework.boot.actuate.health: off

log:
    console-format: ${LOG_FORMAT:json}
    
client:
    analytic:
        host: ${ANALYTIC_HOST}
        port: ${ANALYTIC_PORT}
    parser:
        host: ${PARSER_HOST}
        port: ${PARSER_PORT}